### ISSUE TITLE
Rack alarm warning set at too low a temperature

### ISSUE THREAD

**Issue by vikdhillon** [HiPERCAM/hcam-drivers#126]
With the GTC cooling water now set at +7degC not +5degC, the electronics cabinet seems to be running a few degrees warmer than before, triggering the hdriver alarm at +25degC. Please could this be increased to, say, +30degC, or perhaps it can be made an option in the config file?

**Comment by StuartLittlefair** [comment]
In commit 
https://github.com/HiPERCAM/hcam-drivers/commit/80e2f346e971a197b002d8694ee86e4b9591ae23 I have updated the config file so that alarm thresholds for all hardware can be set in the config file saved in `~/.hdriver/config`.

See the names used in 
https://github.com/HiPERCAM/hcam-drivers/blob/master/hcam_drivers/data/config for details of how to set these values
